language: python

python:
  - "3.7"

install:
  # install system utilities
  - sudo apt-get update --fix-missing
  - sudo apt-get install -yq --no-install-recommends curl bzip2 xz-utils git ca-certificates coinor-cbc
  
  # install conda
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  
  # install conda environment
  - conda env create -f ./environment.yaml
  - conda activate pypsa-eur
  
  # install open-source solver
  - conda install -c conda-forge ipopt

script:
  - cp ./test/config.test1.yaml ./config.yaml
  - snakemake
  - rm -rf resources/*.nc resources/*.geojson resources/*.h5 networks results
  # could repeat for more configurations in future
