os: 
  - windows
  - linux
  - osx

jobs:
  allow_failures:
    - os: osx
    - os: windows

language: bash

before_install:
  # install conda
  - wget https://raw.githubusercontent.com/trichter/conda4travis/latest/conda4travis.sh -O conda4travis.sh
  - source conda4travis.sh
  
  # install conda environment
  - conda env create -f ./environment.yaml
  - conda activate pypsa-eur
  
  # install open-source solver
  - conda install -c conda-forge ipopt glpk

script:
  - cp ./test/config.test1.yaml ./config.yaml
  - snakemake
  - snakemake results/networks/elec_s_6_lcopt_Co2L-24H.nc
  - rm -rf resources/*.nc resources/*.geojson resources/*.h5 networks results
  # could repeat for more configurations in future
