version: 0.1
logging_level: INFO

summary_dir: results

scenario:
  sectors: [E] # ,E+EV,E+BEV,E+BEV+V2G] # [ E+EV, E+BEV, E+BEV+V2G ]
  simpl: ['']
  lv: [1.0, 1.125, 1.25, 1.5, 2.0, 3.0, 'inf']
  clusters: [37, 45, 64, 90, 128, 181, 256, 362, 512] # (2**np.r_[5.5:9:.5]).astype(int)
  opts: [Co2L-3H] #, LC-FL, LC-T, Ep-T, Co2L-T]

countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK'] 

snapshots:
  # arguments to pd.date_range
  start: "2013-01-01"
  end: "2014-01-01"
  closed: 'left' # end is not inclusive

enable:
  powerplantmatching: false
  prepare_links_p_nom: false

electricity:
  voltages: [220., 300., 380.]
  co2limit: 7.75e+7 # 0.05 * 3.1e9*0.5

  extendable_carriers:
    Generator: [OCGT]
    StorageUnit: [battery, H2] # [CAES]

  max_hours:
    battery: 6
    H2: 168

  conventional_carriers: [] # nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]

atlite:
  nprocesses: 4
  cutouts:
    europe-2013-era5:
      module: era5
      xs: [-12., 35.]
      ys: [72., 33.]
      years: [2013, 2013]
    europe-2013-sarah:
      module: sarah
      resolution: 0.2
      xs: [-12., 42.]
      ys: [65., 33.]
      years: [2013, 2013]

renewable:
  onwind:
    cutout: europe-2013-era5
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    # ScholzPhd Tab 4.3.1: 10MW/km^2
    capacity_per_sqkm: 3
    # correction_factor: 0.93
    corine:
      #The selection of CORINE Land Cover [1] types that are allowed for wind and solar are based on [2] p.42 / p.28
      #
      #[1] https://www.eea.europa.eu/ds_resolveuid/C9RK15EA06
      #
      #[2] Scholz, Y. (2012). Renewable energy based electricity supply at low costs: development of the REMix model and application for Europe.
      grid_codes: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
                   24, 25, 26, 27, 28, 29, 31, 32]
      distance: 1000
      distance_grid_codes: [1, 2, 3, 4, 5, 6]
    natura: true
    potential: conservative # or heuristic
  offwind:
    cutout: europe-2013-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
    # ScholzPhd Tab 4.3.1: 10MW/km^2
    capacity_per_sqkm: 3
    # correction_factor: 0.93
    corine: [44, 255]
    natura: true
    max_depth: 50
    potential: conservative # or heuristic
  solar:
    cutout: europe-2013-sarah
    resource:
      method: pv
      panel: CSi
      orientation:
        slope: 35.
        azimuth: 180.
    # ScholzPhd Tab 4.3.1: 170 MW/km^2
    capacity_per_sqkm: 1.7
    correction_factor: 0.877
    corine: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
             14, 15, 16, 17, 18, 19, 20, 26, 31, 32]
    natura: true
    potential: conservative # or heuristic
  hydro:
    cutout: europe-2013-era5
    carriers: [ror, PHS, hydro]
    PHS_max_hours: 6
    hydro_max_hours: "energy_capacity_totals_by_country" # one of energy_capacity_totals_by_country,
                                                         # estimate_by_large_installations or a float


lines:
  types:
    220.: "Al/St 240/40 2-bundle 220.0"
    300.: "Al/St 240/40 3-bundle 300.0"
    380.: "Al/St 240/40 4-bundle 380.0"

  s_max_pu: 0.7
  length_factor: 1.25
  under_construction: 'zero' # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity

links:
  p_max_pu: 1.0
  include_tyndp: true
  under_construction: 'zero' # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity

transformers:
  x: 0.1
  s_nom: 2000.
  type: ''

costs:
  year: 2030

  # From a Lion Hirth paper, also reflects average of Noothout et al 2016
  discountrate: 0.07
  # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html # noqa: E501
  USD2013_to_EUR2013: 0.7532

  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   Wind: Bla
  marginal_cost: # 
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    battery: 0.

  emission_prices: # only used with the option Ep (emission prices)
    co2: 0.

solving:
  options:
    formulation: kirchhoff
    clip_p_max_pu: 1.e-2
    load_shedding: true
    noisy_costs: true
    min_iterations: 4
    # max_iterations: 6
    max_iterations: 3
    #nhours: 10
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
  # solver:
  #   name: cplex
  #   threads: 4
  #   lpmethod: 4 # barrier
  #   solutiontype: 2 # non basic solution, ie no crossover
  #   barrier.convergetol: 1.e-5
  #   feasopt.tolerance: 1.e-6

plotting:
  map:
    figsize: [7, 7]
    boundaries: [-10.2, 29, 35,  72]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 3.e+3 # 1.e+3  #3.e+3

  costs_max: 800
  costs_threshold: 1


  energy_max: 15000.
  energy_min: -10000.
  energy_threshold: 50.


  vre_techs: ["onwind", "offwind", "solar", "ror"]
  conv_techs: ["OCGT", "CCGT", "Nuclear", "Coal"]
  storage_techs: ["hydro+PHS", "battery", "H2"]
  # store_techs: ["Li ion", "water tanks"]
  load_carriers: ["AC load"] #, "heat load", "Li ion load"]
  AC_carriers: ["AC line", "AC transformer"]
  link_carriers: ["DC line", "Converter AC-DC"] 
  heat_links: ["heat pump", "resistive heater", "CHP heat", "CHP electric",
               "gas boiler", "central heat pump", "central resistive heater", "central CHP heat",
               "central CHP electric", "central gas boiler"]
  heat_generators: ["gas boiler", "central gas boiler", "solar thermal collector", "central solar thermal collector"]
  tech_colors:
    "onwind" : "b"
    "onshore wind" : "b"
    'offwind' : "c"
    'offshore wind' : "c"
    "hydro" : "#3B5323"
    "hydro+PHS" : "#3B5323"
    "hydro reservoir" : "#3B5323"
    "ror" : "#78AB46"
    "run of river" : "#78AB46"
    'hydroelectricity' : '#006400'
    'solar' : "y"
    'solar PV' : "y"
    'solar thermal' : 'coral'
    "OCGT" : "wheat"
    "OCGT marginal" : "sandybrown"
    "OCGT-heat" : "orange"
    "gas boiler" : "orange"
    "gas boilers" : "orange"
    "gas boiler marginal" : "orange"
    "gas" : "brown"
    "natural gas" : "brown"
    "lines" : "k"
    "transmission lines" : "k"
    "H2" : "m"
    "hydrogen storage" : "m"
    "battery" : "slategray"
    "battery storage" : "slategray"
    "Nuclear" : "r"
    "Nuclear marginal" : "r"
    "Coal" : "k"
    "Coal marginal" : "k"
    "Lignite" : "grey"
    "Lignite marginal" : "grey"
    "CCGT" : "orange"
    "CCGT marginal" : "orange"
    "heat pumps" : "#76EE00"
    "heat pump" : "#76EE00"
    "air heat pump" : "#76EE00"
    "ground heat pump" : "#40AA00"
    "resistive heater" : "pink"
    "Sabatier" : "#FF1493"
    "methanation" : "#FF1493"
    "helmeth" : "#7D0552"
    "helmeth" : "#7D0552"
    "DAC" : "#E74C3C"
    "nuclear" : "#303030"
    "water tanks" : "#BBBBBB"
    "hot water storage" : "#BBBBBB"
    "hot water charging" : "#BBBBBB"
    "hot water discharging" : "#999999"
    "CHP" : "r"
    "CHP heat" : "r"
    "CHP electric" : "r"
    "PHS" : "g"
    "Ambient" : "k"
    "Electric load" : "b"
    "Heat load" : "r"
    "Transport load" : "grey"
    "heat" : "r"
    "Li ion" : "grey"
    "district heating" : "#CC4E5C"
    "retrofitting" : "purple"
    "building retrofitting" : "purple"
    "BEV charger" : "grey"
    "V2G" : "grey"
    "transport" : "grey"
    "electricity" : "k"
    "transport fuel cell" : "#AAAAAA"
    # _helpers.load_network requirements
    "AC-AC" : "k"
    "AC line" : "k"
  nice_names:
    # OCGT: "Gas"
    # OCGT marginal: "Gas (marginal)"
    offwind: "offshore wind"
    onwind: "onshore wind"
    battery: "Battery storage"
    lines: "Transmission lines"
    AC line: "AC lines"
    AC-AC: "DC lines"
    ror: "Run of river"
  nice_names_n:
    offwind: "offshore\nwind"
    onwind: "onshore\nwind"
    # OCGT: "Gas"
    H2: "Hydrogen\nstorage"
    # OCGT marginal: "Gas (marginal)"
    lines: "transmission\nlines"
    ror: "run of river"
