name: pypsa-eur
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - six
  - snakemake
  - numpy
  - pyomo
  - scipy
  - pandas>=0.22.0
  - matplotlib
  - seaborn
  - memory_profiler
  - networkx>=1.10
  - netcdf4
  - xarray
  - xlrd
  - scikit-learn
  - pytables
  - pycountry

  # Include ipython so that one does not inadvertently drop out of the conda
  # environment by calling ipython
  - ipython

  # GIS dependencies have to come all from conda-forge
  - conda-forge::fiona
  - conda-forge::pyproj
  - conda-forge::pyshp
  - conda-forge::geopandas
  - conda-forge::rasterstats
  - conda-forge::rasterio
  - conda-forge::shapely
  - conda-forge::libgdal

  # The FRESNA/KIT stuff is not packaged for conda yet
  - pip:
    - pypsa>=0.13
    - vresutils>=0.2.5
    - git+https://github.com/FRESNA/atlite.git
    #- git+https://github.com/FRESNA/powerplantmatching.git
    #- https://software.ecmwf.int/wiki/download/attachments/56664858/ecmwf-api-client-python.tgz

