name: pypsa-eur
channels:
  - bioconda
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - affine=2.3.0
  - appdirs=1.4.3
  - asn1crypto=1.2.0
  - atlite=0.0.2
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blosc=1.17.0
  - bokeh=1.3.4
  - boost-cpp=1.68.0
  - bottleneck=1.2.1
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - cairo=1.16.0
  - cartopy=0.17.0
  - certifi=2019.9.11
  - cffi=1.13.1
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.2.2
  - configargparse=0.13.0
  - cryptography=2.7
  - curl=7.65.3
  - cycler=0.10.0
  - cytoolz=0.10.0
  - dask=2.6.0
  - dask-core=2.6.0
  - datrie=0.8
  - decorator=4.4.1
  - distributed=2.6.0
  - docutils=0.15.2
  - expat=2.2.5
  - fiona=1.8.9.post2
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - fsspec=0.5.2
  - gdal=2.4.2
  - geopandas=0.6.1
  - geos=3.7.2
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.1.7
  - gitdb2=2.0.6
  - gitpython=3.0.4
  - glib=2.58.3
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.1
  - icu=58.2
  - idna=2.8
  - importlib_metadata=0.23
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - jedi=0.15.1
  - jinja2=2.10.3
  - joblib=0.14.0
  - jpeg=9c
  - json-c=0.13.1
  - jsonschema=3.1.1
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libdap4=3.20.4
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgdal=2.4.2
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=11.5
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - locket=0.2.0
  - lz4-c=1.8.3
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib-base=3.1.1
  - memory_profiler=0.55.0
  - mock=3.0.5
  - more-itertools=7.2.0
  - msgpack-python=0.6.2
  - munch=2.3.2
  - ncurses=6.1
  - numexpr=2.7.0
  - numpy=1.17.3
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1c
  - owslib=0.18.0
  - packaging=19.2
  - pandas=0.25.2
  - parso=0.5.1
  - partd=1.0.0
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=19.3.1
  - pixman=0.38.0
  - pluggy=0.13.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.5
  - progressbar2=3.47.0
  - proj4=6.1.1
  - prompt_toolkit=2.0.10
  - psutil=5.6.3
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.8.0
  - pycountry=19.8.18
  - pycparser=2.19
  - pyepsg=0.4.0
  - pygments=2.4.2
  - pykdtree=1.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyproj=2.2.2
  - pyrsistent=0.15.4
  - pyshp=2.1.0
  - pysocks=1.7.1
  - pytables=3.5.2
  - pytest=5.0.1
  - pytest-runner=5.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - python-utils=2.3.0
  - pytz=2019.3
  - pyyaml=5.1.2
  - rasterio=1.0.28
  - ratelimiter=1.2.0
  - readline=8.0
  - requests=2.22.0
  - rtree=0.8.3
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - setuptools=41.4.0
  - shapely=1.6.4
  - six=1.12.0
  - smmap2=2.0.5
  - snakemake-minimal=5.7.4
  - snuggs=1.4.7
  - sortedcontainers=2.1.0
  - sqlite=3.30.1
  - statsmodels=0.10.1
  - tbb=2018.0.5
  - tblib=1.4.0
  - tiledb=1.6.2
  - tk=8.6.9
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.3
  - tzcode=2019a
  - urllib3=1.25.6
  - wcwidth=0.1.7
  - wheel=0.33.6
  - wrapt=1.11.2
  - xarray=0.14.0
  - xerces-c=3.2.2
  - xlrd=1.2.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zict=1.0.0
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.0
  - pip:
    - beautifulsoup4==4.8.1
    - cdsapi==0.2.3
    - countrycode==0.2
    - descartes==1.1.0
    - entsoe-py==0.2.10
    - geographiclib==1.50
    - geokit==1.1.2
    - geopy==1.20.0
    - glaes==1.1.2
    - networkx==2.4
    - nose==1.3.7
    - ply==3.11
    - powerplantmatching==0.4.1
    - pyomo==5.6.6
    - pypsa==0.14.1
    - pyutilib==5.7.1
    - soupsieve==1.9.4
    - tqdm==4.36.1
    - vresutils==0.3
