name: pypsa-eur
channels:
  - bioconda
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - affine=2.3.0
  - appdirs=1.4.3
  - atlite=0.0.2
  - attrs=19.3.0
  - backcall=0.1.0
  - beautifulsoup4=4.8.2
  - blosc=1.17.0
  - bokeh=1.4.0
  - boost-cpp=1.70.0
  - bottleneck=1.3.1
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - cartopy=0.17.0
  - certifi=2019.11.28
  - cffi=1.13.2
  - cfitsio=3.470
  - cftime=1.0.4.2
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.2.2
  - configargparse=0.13.0
  - cryptography=2.8
  - curl=7.65.3
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask=2.9.1
  - dask-core=2.9.1
  - datrie=0.8
  - dbus=1.13.6
  - decorator=4.4.1
  - distributed=2.9.1
  - docutils=0.15.2
  - entsoe-py=0.2.10
  - expat=2.2.5
  - fiona=1.8.6
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - fsspec=0.6.2
  - gdal=2.4.1
  - geographiclib=1.50
  - geopandas=0.6.2
  - geopy=1.20.0
  - geos=3.7.2
  - geotiff=1.4.3
  - gettext=0.19.8.1
  - giflib=5.1.7
  - gitdb2=2.0.6
  - gitpython=3.0.5
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - hdf4=4.2.13
  - hdf5=1.10.5
  - heapdict=1.0.1
  - icu=58.2
  - idna=2.8
  - importlib_metadata=1.3.0
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - jedi=0.15.2
  - jinja2=2.10.3
  - joblib=0.14.1
  - jpeg=9c
  - json-c=0.13.1
  - jsonschema=3.2.0
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libdap4=3.20.4
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgdal=2.4.1
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=11.5
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - locket=0.2.0
  - lz4-c=1.8.3
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - memory_profiler=0.56.0
  - mock=3.0.5
  - more-itertools=8.0.2
  - msgpack-python=0.6.2
  - munch=2.5.0
  - ncurses=6.1
  - netcdf4=1.5.1.2
  - networkx=2.4
  - nose=1.3.7
  - numexpr=2.7.1
  - numpy=1.17.3
  - olefile=0.46
  - openjpeg=2.3.1
  - openmp_impl=4.5
  - openssl=1.1.1d
  - owslib=0.19.0
  - packaging=20.0
  - pandas=0.25.3
  - parso=0.5.2
  - partd=1.1.0
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=19.3.1
  - pixman=0.38.0
  - pluggy=0.13.0
  - ply=3.11
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.5
  - powerplantmatching=0.4.3
  - progressbar2=3.47.0
  - proj4=5.2.0
  - prompt_toolkit=3.0.2
  - psutil=5.6.7
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.8.1
  - pycountry=19.8.18
  - pycparser=2.19
  - pyepsg=0.4.0
  - pygments=2.5.2
  - pykdtree=1.3.1
  - pyomo=5.6.8
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyproj=1.9.6
  - pypsa=0.16.0
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - pyshp=2.1.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=5.3.2
  - pytest-runner=5.2
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-utils=2.3.0
  - pytz=2019.3
  - pyutilib=5.7.3
  - pyyaml=5.3
  - qt=5.9.7
  - rasterio=1.0.25
  - ratelimiter=1.2.0
  - readline=8.0
  - requests=2.22.0
  - rtree=0.9.3
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.9.0
  - setuptools=44.0.0
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.13.0
  - smmap2=2.0.5
  - snakemake-minimal=5.9.1
  - snuggs=1.4.7
  - sortedcontainers=2.1.0
  - soupsieve=1.9.4
  - sqlite=3.30.1
  - statsmodels=0.10.2
  - tblib=1.6.0
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.3
  - tzcode=2019a
  - urllib3=1.25.7
  - wcwidth=0.1.8
  - wheel=0.33.6
  - wrapt=1.11.2
  - xarray=0.14.1
  - xerces-c=3.2.2
  - xlrd=1.2.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.2.2
  - zict=1.0.0
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - cdsapi==0.2.5
    - countrycode==0.2
    - descartes==1.1.0
    - geokit==1.1.2
    - glaes==1.1.2
    - tqdm==4.41.1
    - vresutils==0.3
