name: pypsa-eur
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - six
  - snakemake
  - numpy
  - pyomo
  - scipy
  - pandas>=0.22.0
  - matplotlib
  - seaborn
  - memory_profiler
  - networkx>=1.10
  - xlrd
  - scikit-learn
  - pytables
  - pycountry

  # Second order dependencies which should really be deps of atlite
  - xarray
  - netcdf4
  - bottleneck
  - cyordereddict
  - toolz
  - dask
  - progressbar2

  # Include ipython so that one does not inadvertently drop out of the conda
  # environment by calling ipython
  - ipython

  # GIS dependencies have to come all from conda-forge
  - conda-forge::fiona
  - conda-forge::pyproj
  - conda-forge::pyshp
  - conda-forge::geopandas
  - conda-forge::rasterstats
  - conda-forge::rasterio
  - conda-forge::shapely
  - conda-forge::libgdal

  # The FRESNA/KIT stuff is not packaged for conda yet
  - pip:
    - pypsa>=0.13.2
    - vresutils>=0.2.5
    - git+https://github.com/FRESNA/atlite.git#egg=atlite
    - git+https://github.com/PyPSA/glaes.git#egg=glaes
    - git+https://github.com/PyPSA/geokit.git#egg=geokit
    #- git+https://github.com/FRESNA/powerplantmatching.git#egg=powerplantmatching
    #- https://software.ecmwf.int/wiki/download/attachments/56664858/ecmwf-api-client-python.tgz

