name: pypsa-eur
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pip
  - conda>=4.8.1

  - pypsa>=0.16
  - atlite

  # Dependencies of the workflow itself
  - xlrd
  - scikit-learn
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - yaml
  - pytables
  - powerplantmatching>=0.4.3

  # Second order dependencies which should really be deps of atlite
  - xarray
  - netcdf4
  - bottleneck
  - toolz
  - dask
  - progressbar2
  - pyyaml>=5.1.0

  # Include ipython so that one does not inadvertently drop out of the conda
  # environment by calling ipython
  - ipython

  # GIS dependencies:
  - cartopy
  - fiona
  - proj
  - pyshp
  - geopandas
  - rasterio
  - shapely
  - libgdal

  - pip:
    - git+https://github.com/FRESNA/vresutils.git#egg=vresutils
    - git+https://github.com/PyPSA/glaes.git#egg=glaes
    - git+https://github.com/PyPSA/geokit.git#egg=geokit
    - cdsapi
